// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MihuBot.DB;

#nullable disable

namespace MihuBot.Migrations.MollyDb
{
    [DbContext(typeof(MollyDbContext))]
    partial class MollyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MihuBot.Molly.MollyAlertDbEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("mollyAlerts");
                });

            modelBuilder.Entity("MihuBot.Molly.MollyDbEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CreatedDay")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DerivedHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedNickname")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EncryptedServerHmac")
                        .HasColumnType("BLOB");

                    b.Property<int>("HashPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LastSeenDay")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockRequested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WipeRequested")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashPrefix");

                    b.ToTable("mollyEntries");
                });

            modelBuilder.Entity("MihuBot.Molly.MollyAlertDbEntry", b =>
                {
                    b.HasOne("MihuBot.Molly.MollyDbEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });
#pragma warning restore 612, 618
        }
    }
}
