// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MihuBot.DB.GitHub;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace MihuBot.Migrations.GitHubDb
{
    [DbContext(typeof(GitHubDbContext))]
    [Migration("20251027091733_AddDiscussions")]
    partial class AddDiscussions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssueInfoLabelInfo", b =>
                {
                    b.Property<string>("IssuesId")
                        .HasColumnType("text");

                    b.Property<string>("LabelsId")
                        .HasColumnType("text");

                    b.HasKey("IssuesId", "LabelsId");

                    b.HasIndex("LabelsId");

                    b.ToTable("IssueInfoLabelInfo");
                });

            modelBuilder.Entity("IssueInfoUserInfo", b =>
                {
                    b.Property<string>("AssignedIssuesId")
                        .HasColumnType("text");

                    b.Property<long>("AssigneesId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignedIssuesId", "AssigneesId");

                    b.HasIndex("AssigneesId");

                    b.ToTable("IssueInfoUserInfo");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.CommentInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AuthorAssociation")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("Confused")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Eyes")
                        .HasColumnType("integer");

                    b.Property<long>("GitHubIdentifier")
                        .HasColumnType("bigint");

                    b.Property<int>("Heart")
                        .HasColumnType("integer");

                    b.Property<int>("Hooray")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsMinimized")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrReviewComment")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastObservedDuringFullRescanTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Laugh")
                        .HasColumnType("integer");

                    b.Property<string>("MinimizedReason")
                        .HasColumnType("text");

                    b.Property<int>("Minus1")
                        .HasColumnType("integer");

                    b.Property<int>("Plus1")
                        .HasColumnType("integer");

                    b.Property<int>("Rocket")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.IssueInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("ActiveLockReason")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorAssociation")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Confused")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Eyes")
                        .HasColumnType("integer");

                    b.Property<int>("Heart")
                        .HasColumnType("integer");

                    b.Property<int>("Hooray")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text");

                    b.Property<int>("IssueType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastObservedDuringFullRescanTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSemanticIngestionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Laugh")
                        .HasColumnType("integer");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("MilestoneId")
                        .HasColumnType("text");

                    b.Property<int>("Minus1")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Plus1")
                        .HasColumnType("integer");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rocket")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("Number");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("issues");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.LabelInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("labels");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.MilestoneInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClosedIssueCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("OpenIssueCount")
                        .HasColumnType("integer");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Title");

                    b.ToTable("milestones");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.PullRequestInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Additions")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<bool>("MaintainerCanModify")
                        .HasColumnType("boolean");

                    b.Property<int?>("Mergeable")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MergedById")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("pullrequests");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.RepositoryInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscussionRescanCursor")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text");

                    b.Property<bool>("InitialIngestionInProgress")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueRescanCursor")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastForceRescanStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFullRescanStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastFullRescanTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastIssueCommentsUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastIssuesUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPullRequestReviewCommentsUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRepositoryMetadataUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NodeIdentifier")
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<string>("PullRequestRescanCursor")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.SemanticIngestionBacklogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("semantic_ingestion_backlog");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.TextEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("TextVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Text" });

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("TextVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TextVector"), "GIN");

                    b.ToTable("text_entries");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.UserInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<int>("Following")
                        .HasColumnType("integer");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NodeIdentifier")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeIdentifier");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MihuBot.DB.Models.BodyEditHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsComment")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousBody")
                        .HasColumnType("text");

                    b.Property<string>("ResourceIdentifier")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("body_edit_history");
                });

            modelBuilder.Entity("MihuBot.DB.Models.IngestedEmbeddingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<long>("RepositoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ingested_embedding_records");
                });

            modelBuilder.Entity("MihuBot.DB.Models.TriagedIssueRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("IssueId")
                        .HasColumnType("text");

                    b.Property<int>("TriageReportIssueNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("triaged_issues");
                });

            modelBuilder.Entity("IssueInfoLabelInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.IssueInfo", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MihuBot.DB.GitHub.LabelInfo", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IssueInfoUserInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.IssueInfo", null)
                        .WithMany()
                        .HasForeignKey("AssignedIssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MihuBot.DB.GitHub.UserInfo", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.CommentInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.IssueInfo", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId");

                    b.HasOne("MihuBot.DB.GitHub.UserInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.IssueInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.MilestoneInfo", "Milestone")
                        .WithMany("Issues")
                        .HasForeignKey("MilestoneId");

                    b.HasOne("MihuBot.DB.GitHub.RepositoryInfo", "Repository")
                        .WithMany("Issues")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MihuBot.DB.GitHub.UserInfo", "User")
                        .WithMany("Issues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.LabelInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.RepositoryInfo", "Repository")
                        .WithMany("Labels")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.MilestoneInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.RepositoryInfo", "Repository")
                        .WithMany("Milestones")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.PullRequestInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.IssueInfo", "Issue")
                        .WithOne("PullRequest")
                        .HasForeignKey("MihuBot.DB.GitHub.PullRequestInfo", "IssueId");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.RepositoryInfo", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.UserInfo", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MihuBot.DB.Models.TriagedIssueRecord", b =>
                {
                    b.HasOne("MihuBot.DB.GitHub.IssueInfo", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.IssueInfo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.MilestoneInfo", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.RepositoryInfo", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Labels");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("MihuBot.DB.GitHub.UserInfo", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
