name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    if: github.repository == 'MihaZupan/MihuBot' && contains(github.event.head_commit.message, 'docker')
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./deploy
          file: ./deploy/Dockerfile
          push: true
          tags: mihazupan/mihubot:latest
